stages:
  - build
  - lint
  - test

build:
  image: node:16-alpine
  only:
    - merge_requests
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
      when: always
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

lint:
  image: node:16-alpine
  only:
    - merge_requests
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
      when: always
  script:
    - npm install
    - npm run lint

test:
  image: node:16-alpine
  only:
    - merge_requests
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
      when: always
  script:
    - npm install
    - npm run test
