image: node:16

cache:
  paths:
    - node_modules/

stages:
  - build
  - lint
  - test
  - deploy

build:
  stage: build
  only:
    - develop
    - master
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

lint:
  stage: lint
  image: node:16-alpine
  only:
    - develop
    - master
  script:
    - npm install
    - npm run lint

test:
  stage: test
  image: node:16-alpine
  only:
    - develop
    - master
  script:
    - npm install
    - npm run test

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push  $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - master
