version: '3.7'

services:
  database:
    image: postgres:latest
    container_name: datbase_container
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=o2database
    volumes:
      - ./.volumes/postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
  api:
    container_name: rest_o2_container
    build: '.'
    restart: always
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASS=123
      - DATABASE_HOST=database
    links:
      - database
    ports:
      - '3001:3000'
    depends_on:
      - database
